routes/web.php
<?php

Route::group(['middleware' => 'guest'], function() {
    Route::view('/', 'login')->name('index');
    Route::post('/login', 'LoginController')->name('login');
});

Route::group(['middleware' => 'auth', 'prefix' => 'admin', 'as' => 'admin.'], function() {
    Route::get('/', 'AdminController@index')->name('index');
    Route::get('/{payment}/show', 'AdminController@show')->name('show');
    Route::view('/add', 'admin.add')->name('add');
    Route::post('/store', 'AdminController@store')->name('store');
});

Route::get('payment/{payment_hash}', 'PaymentController')->name('payment');
Route::get('payment/{payment_hash}/process', 'PaymentProcessController@process')->name('payment.process');

app/Payment.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Payment extends Model
{
    protected $guarded = ['id'];
    protected $dates = [
        'paid_at',
    ];
    const STATUS_PENDING = 'pending';
    const STATUS_SUCCESS = 'success';
    const STATUS_ERROR = 'error';

    public static function boot()
    {
        parent::boot();
        self::creating(function ($model) {
            $model->status = self::STATUS_PENDING;
        });
    }

    public static function statuses()
    {
        return [
            self::STATUS_PENDING => 'В ожидании оплаты',
            self::STATUS_SUCCESS => 'Оплата прошла успешно',
            self::STATUS_ERROR => 'Оплата завершена с ошибками',
        ];
    }

    public function getStatusLabelAttribute()
    {
        return $this->statuses()[$this->status] ?? '';
    }

    public function getPayerCardHiddenAttribute()
    {
        return substr($this->payer_card, 0, 6) . '******' . substr($this->payer_card,  -4);
    }

    public function payable()
    {
        return $this->status === self::STATUS_PENDING;
    }

    public function finished()
    {
        return $this->status === self::STATUS_SUCCESS || $this->status === self::STATUS_ERROR;
    }

    public static function cutAmount($amount)
    {
        return intval($amount * 100) / 100;

        [$num, $float] = explode('.', $amount);
        return sprintf('%s.%s%s',
            $num,
            $float[0] ?? 0,
            $float[1] ?? ''
        );
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/AdminController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StorePaymentRequest;
use App\Payment;
use Illuminate\Http\Request;

class AdminController
{
    public function index(Request $request)
    {
        $items = Payment::query()
            ->when($request->filled('status'), function($query) {
                $query->where('status', request()->input('status'));
            })
            ->latest()
            ->paginate(10);

        return view('admin.index', compact('items'));
    }

    public function show(Payment $payment)
    {
        return view('admin.show', compact('payment'));
    }

    public function store(StorePaymentRequest $request)
    {
        $payment = Payment::create([
           'payer_phone' => $request->input('payer_phone'),
           'payer_email' => $request->input('payer_email'),
           'amount' => $request->input('amount'),
        ]);

        return redirect()->route('admin.show', ['payment' => $payment->id]);
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/LoginController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\LoginRequest;
use Illuminate\Support\Facades\Auth;

class LoginController
{
    public function __invoke(LoginRequest $request)
    {
        if (!Auth::attempt($request->only(['email', 'password']))) {
            return redirect()->back()->withErrors(['incorrect email or password']);
        }

        return redirect()->route('admin.index');
    }
}

app/Http/Controllers/PaymentController.php
<?php

namespace App\Http\Controllers;

use App\Payment;

class PaymentController
{
    public function __invoke(Payment $payment)
    {
        if ($payment->payable()) {
            return view('payment-init', compact('payment'));
        }

        return view('payment-check', compact('payment'));
    }
}

app/Http/Controllers/PaymentProcessController.php
<?php

namespace App\Http\Controllers;

use App\Payment;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use App\Rules\ValidCardDate;
use App\Rules\ValidCardNumber;

class PaymentProcessController
{
    public function process(Payment $payment, Request $request)
    {
        $payment->payer_phone = $request->input('payer_phone');
        $payment->payer_email = $request->input('payer_email');
        $payment->payer_card = $request->input('payer_card');
        $payment->paid_at = now();

        $validator = Validator::make($request->all(), [
            'payer_phone' => 'required',
            'payer_email' => 'email',
            'payer_card' => ['required', 'numeric', new ValidCardNumber, new ValidCardDate],
            'payer_card_month' => 'required|numeric|between:1,12',
            'payer_card_year' => 'required|numeric|between:2019,2030',
        ]);

        if ($validator->fails()) {
            $payment->status = Payment::STATUS_ERROR;
            $payment->save();

            return redirect()
                ->back()
                ->withErrors($validator)
                ->withInput();
        }
        $payment->status = Payment::STATUS_SUCCESS;
        $payment->save();

        return redirect()->back();
    }
}

resources/views/_partials/errors.blade.php
@isset ($errors)
    @foreach ($errors->all() as $error)
        <div class="message is-danger">
            <div class="message-header">
                <p>Danger</p>
            </div>
            <div class="message-body">{{ $error }}</div>
        </div>
    @endforeach
@endif

resources/views/admin/add.blade.php
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title></title>
    <link rel="stylesheet" href="/css/bulma.min.css">
    <link rel="stylesheet" href="/css/app.css">
</head>
<body>
<section class="section">
    <div class="container">
        <nav class="breadcrumb" aria-label="breadcrumbs">
            <ul>
                <li><a href="/">Home</a></li>
                <li><a href="{{ route('admin.index') }}" aria-current="page">Payment list</a></li>
                <li class="is-active"><a aria-current="page">Store payment</a></li>
            </ul>
        </nav>
        <form class="content" action="{{ route('admin.store') }}"method="post">
            @csrf
            @include('_partials.errors')
            <div class="field is-horizontal">
                <div class="field-label is-normal">
                    <label class="label">Данные плательщика</label>
                </div>
                <div class="field-body">
                    <div class="field">
                        <p class="control is-expanded has-icons-left has-icons-right">
                            <input class="input" type="email" placeholder="Email" name="payer_email" value="">
                            <span class="icon is-small is-left">
                              <i class="fas fa-envelope"></i>
                            </span>
                            <span class="icon is-small is-right">
                              <i class="fas fa-check"></i>
                            </span>
                        </p>
                    </div>
                    <div class="field">
                        <p class="control is-expanded has-icons-left">
                            <input class="input" type="tel" placeholder="Your phone number" name="payer_phone">
                            <span class="icon is-small is-left">
                              <i class="fas fa-user"></i>
                            </span>
                        </p>
                    </div>
                </div>
            </div>

            <div class="field is-horizontal">
                <div class="field-label is-normal">
                    <label class="label">Amount</label>
                </div>
                <div class="field-body">
                    <div class="field">
                        <div class="control">
                            <input class="input" type="text" placeholder="amount" name="amount" required>
                        </div>
                        <p class="help is-danger">
                            This field is required
                        </p>
                    </div>
                </div>
            </div>

            <div class="field is-horizontal">
                <div class="field-label">
                </div>
                <div class="field-body">
                    <div class="field">
                        <div class="control">
                            <button class="button is-primary">
                                Send
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</section>
</body>
</html>

resources/views/admin/index.blade.php
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title></title>
    <link rel="stylesheet" href="/css/bulma.min.css">
    <link rel="stylesheet" href="/css/app.css">
</head>
<body>
<section class="section">
    <div class="container">
        <nav class="breadcrumb" aria-label="breadcrumbs">
            <ul>
                <li><a href="/">Home</a></li>
                <li class="is-active"><a href="#" aria-current="page">Payment list</a></li>
            </ul>
        </nav>
        <a class="button is-primary" href="{{ route('admin.add') }}">Выставить счет</a>
        <form class="is-grouped">
            <div>Статус: </div>
            <div class="select">
                <select name="status">
                    <option value="">Все</option>
                    @foreach(\App\Payment::statuses() as $id => $name)
                        <option value="{{ $id }}" {{ request()->input('status') === $id ? 'selected' : '' }}>{{ $name }}</option>
                    @endforeach
                </select>
            </div>
            <button class="button is-primary">Отправить</button>
        </form>
        <table class="table table-container table-responsive table-bordered">
            <thead>
            <tr>
                <th>ID</th>
                <th>Amount</th>
                <th>Status</th>
                <th>Paid at</th>
                <th>Created at</th>
                <th>Actions</th>
            </tr>
            </thead>
            <tbody>
            @foreach ($items as $item)
                <tr>
                    <td>{{ $item->id }}</td>
                    <td>{{ $item->amount }}</td>
                    <td>{{ $item->status_label }}</td>
                    <td>{{ $item->paid_at }}</td>
                    <td>{{ $item->created_at->format('d.m.Y H:i:s') }}</td>
                    <td><a class="button" href="{{ route('admin.show', ['payment' => $item->id]) }}">Show</a></td>
                </tr>
            @endforeach
            </tbody>
        </table>
        {{ $items->links() }}
    </div>
</section>
</body>
</html>

resources/views/admin/show.blade.php
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title></title>
    <link rel="stylesheet" href="/css/bulma.min.css">
    <link rel="stylesheet" href="/css/app.css">
</head>
<body>
<section class="section">
    <div class="container">
        <nav class="breadcrumb" aria-label="breadcrumbs">
            <ul>
                <li><a href="/">Home</a></li>
                <li><a href="{{ route('admin.index') }}" aria-current="page">Payment list</a></li>
                <li class="is-active"><a aria-current="page">Payment #{{ $payment->id }}</a></li>
            </ul>
        </nav>
        <div class="content">
            <h3>Данные о платеже</h3>
            <div><b>ID:</b> {{ $payment->id }}</div>
            <div><b>Amount:</b> {{ $payment->amount }}тг.</div>
            <div><b>Status:</b> {{ $payment->status_label }}</div>
            <div><b>Created at:</b> {{ $payment->created_at->format('d.m.Y H:i:s') }}</div>
            @if ($payment->finished())
                <h3>Данные об оплате</h3>
                <div>
                    <b>Время оплаты:</b> {{ $payment->paid_at->format('d.m.Y H:i:s') }} <span class="tag is-primary">{{ $payment->paid_at->diffForHumans($payment->created_at) }}</span>
                </div>
                <div><b>Телефон плательщика:</b> {{ $payment->payer_phone }}</div>
                <div><b>Email:</b> {{ $payment->payer_email }}</div>
                <div><b>Карта:</b> {{ $payment->payer_card_hidden }}</div>
            @else
                <h3>Ссылка для оплаты</h3>
                <div class="field is-grouped">
                    <p class="control is-expanded">
                        <input class="input text-url" type="text" readonly value="{{ route('payment', ['payment_hash' => encrypt($payment->id)]) }}">
                    </p>
                    <p class="control">
                        <button class="button is-info button-copy">
                            Copy
                        </button>
                    </p>
                </div>
            @endif
        </div>
    </div>
</section>
<script>
    var btn = document.querySelector('.button-copy');
    btn.addEventListener('click', function(event) {
        var copyTextarea = document.querySelector('.text-url');
        copyTextarea.focus();
        copyTextarea.select();
        document.execCommand('copy');
        btn.innerText = 'Copied!';
    });
</script>
</body>
</html>

resources/views/login.blade.php
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Login page</title>
    <link rel="stylesheet" href="/css/bulma.min.css">
    <link rel="stylesheet" href="/css/app.css">
</head>
<body>
<section class="section">
    <div class="container">
        <div class="columns">
            <form action="{{ route('login') }}" method="post" class="column is-two-fifths">
                @csrf
                <h1 class="title">Введите ваши данные</h1>

                @isset ($errors)
                    @foreach ($errors->all() as $error)
                        <div class="message is-danger">
                            <div class="message-header">
                                <p>Danger</p>
                            </div>
                            <div class="message-body">{{ $error }}</div>
                        </div>
                    @endforeach
                @endif

                <div class="field">
                    <p class="control has-icons-left has-icons-right">
                        <input class="input" type="email" placeholder="admin@admin.com" name="email">
                        <span class="icon is-small is-left">
                  <i class="fas fa-envelope"></i>
                </span>
                        <span class="icon is-small is-right">
                  <i class="fas fa-check"></i>
                </span>
                    </p>
                </div>
                <div class="field">
                    <p class="control has-icons-left">
                        <input class="input" type="password" placeholder="1234" name="password">
                        <span class="icon is-small is-left">
                  <i class="fas fa-lock"></i>
                </span>
                    </p>
                </div>
                <div class="field">
                    <p class="control">
                        <button class="button is-success">
                            Login
                        </button>
                    </p>
                </div>
            </form>
        </div>
    </div>
</section>
</body>
</html>

resources/views/payment-check.blade.php
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title></title>
    <link rel="stylesheet" href="/css/bulma.min.css">
    <link rel="stylesheet" href="/css/app.css">
</head>
<body>
<section class="section">
    <div class="container">
        <div class="columns  is-centered">
            <div class="column is-3">

                <div style="padding: 10px 10px 10px 10px; border: 1px solid gray; border-radius: 5px;">

                    <nav class="level">
                        <div class="level-item">
                            <p style="text-align: center; font-weight: bold; color: #2d3436">{{ $payment->status_label }}</p>
                        </div>
                    </nav>

                    <nav class="level">

                        <div class="level-item">
                            <p style="text-align: center; font-size: 28px; font-weight: bold; color: #25c151">
                                {{ $payment->amount }}
                                <span style="color: gray; font-weight: normal; font-size: 20px;">тг.</span>
                            </p>
                        </div>
                    </nav>

                    <p style="text-align: center; font-size: 18px;">

                        @include('_partials.errors')
                        Оплачен {{ $payment->paid_at }}
                    {{--
                    <div>{{ \App\Payment::cutAmount(8.256) }}</div>
                    <div>{{ \App\Payment::cutAmount(10.1) }}</div>
                    <div>{{ \App\Payment::cutAmount(-0.128) }}</div>
                    --}}
                    </p>

                    <nav class="level" style="margin-top: 20px;">
                        <div class="level-item">
                            <div>
                                <button class="button" style="margin-top: 10px; background-color: #25c151; color: white; font-weight: bold; text-transform: uppercase;">
                                    Распечатать чек
                                </button>
                                <p style="text-align: center; font-size: 12px; margin-top: 5px;">
                                    просто кнопка :)
                                </p>
                            </div>
                        </div>
                    </nav>
                </div>
            </div>
        </div>
    </div>
</section>
</body>
</html>

resources/views/payment-init.blade.php
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title></title>
    <link rel="stylesheet" href="/css/bulma.min.css">
    <link rel="stylesheet" href="/css/app.css">
</head>
<body>
<section class="section">
    <div class="container">
        <div class="columns  is-centered">
            <div class="column is-3">
                @include('_partials.errors')
                <form action="{{ route('payment.process', ['payment_hash' => encrypt($payment->id)]) }}" style="padding: 10px 10px 10px 10px; border: 1px solid gray; border-radius: 5px;">
                    @csrf
                    <nav class="level">
                        <div class="level-item">
                            <p style="text-align: center; font-weight: bold; color: #2d3436">{{ $payment->status_label }}</p>
                        </div>
                    </nav>

                    <nav class="level">

                        <div class="level-item">
                            <p style="text-align: center; font-size: 28px; font-weight: bold; color: #25c151">
                                {{ $payment->amount }}
                                <span style="color: gray; font-weight: normal; font-size: 20px;">тг.</span>
                            </p>
                        </div>
                    </nav>

                    <div>
                        <div class="field">
                            <label class="label">Phone:</label>
                            <div class="control">
                                <input class="input" type="tel" placeholder="+7"  name="payer_phone" value="{{ old('payer_phone', $payment->payer_phone) }}" required>
                            </div>
                        </div>
                        <div class="field">
                            <label class="label">Email:</label>
                            <div class="control">
                                <input class="input" type="email" placeholder="email@email.com" name="payer_email" value="{{ old('payer_email', $payment->payer_email) }}" >
                            </div>
                        </div>
                        <div class="field">
                            <label class="label">Card number:</label>
                            <div class="control">
                                <input class="input" type="number" placeholder="" name="payer_card" required value="{{ old('payer_card') }}">
                            </div>
                        </div>
                        <label class="label">Срок действия карты:</label>
                        <div class="field is-grouped">
                            <div class="control" style="    flex-shrink: inherit;">
                                <input class="input" type="number" placeholder="{{ date('m') }}" name="payer_card_month" required min="{{ date('m') }}" max="12" value="{{ old('payer_card_month') }}">
                            </div>
                            <div class="control" style="    flex-shrink: inherit;">
                                <input class="input" type="number" placeholder="{{ date('Y') }}" name="payer_card_year" required min="{{ date('Y') }}" max="2030" value="{{ old('payer_card_year') }}">
                            </div>
                        </div>
                    </div>

                    <nav class="level" style="margin-top: 20px;">
                        <div class="level-item">
                            <div>
                                <button class="button" style="margin-top: 10px; background-color: #25c151; color: white; font-weight: bold; text-transform: uppercase;">
                                    Оплатить
                                </button>
                                <p style="text-align: center; font-size: 12px; margin-top: 5px;">
                                     Платеж №{{ $payment->id }}
                                </p>
                            </div>
                        </div>
                    </nav>
                </form>
            </div>
        </div>
    </div>
</section>
</body>
</html>